# Generated by Django 4.2.4 on 2023-08-27 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elements', '0002_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='area',
            old_name='kode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='date_modified',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='keterangan',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='tipe',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='faskes',
            old_name='date_modified',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='faskes',
            old_name='keterangan',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='faskes',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='date_modified',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='keterangan',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='nomor',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='isi',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='date_modified',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='judul',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='date_modified',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='date_modified',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='keterangan',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='judul',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='faskes',
            name='lokasi',
        ),
        migrations.RemoveField(
            model_name='option',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='kategori',
        ),
        migrations.AddField(
            model_name='answer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faskes',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faskes',
            name='location',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='elements.area', verbose_name='Location Faskes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faskes',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='option',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='option',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='survey',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No'), (99, 'No Answer')]),
        ),
        migrations.AlterField(
            model_name='area',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': '0'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.area', verbose_name='Parent Area'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.survey', verbose_name='Survey Title'),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AddField(
            model_name='option',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='elements.category', verbose_name='Value Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='elements.category'),
            preserve_default=False,
        ),
    ]
