# Generated by Django 4.2.4 on 2023-08-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_alter_answer_created_by_alter_answer_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='number',
            field=models.IntegerField(editable=False),
        ),
    ]
