# Generated by Django 4.2.4 on 2023-08-29 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0007_rename_name_respondent_nama_respondent_faskes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gender_Category', to='elements.option'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='jarnas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jarnas_Category', to='elements.option'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='usia',
            field=models.ForeignKey(limit_choices_to={'category__title': 'Usia'}, on_delete=django.db.models.deletion.CASCADE, related_name='Usia_Category', to='elements.option'),
        ),
    ]
