# Generated by Django 4.2.4 on 2023-08-29 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0008_alter_respondent_gender_alter_respondent_jarnas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='gender',
            field=models.ForeignKey(limit_choices_to={'category__title': 'Gender'}, on_delete=django.db.models.deletion.CASCADE, related_name='Gender_Category', to='elements.option'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='jarnas',
            field=models.ForeignKey(limit_choices_to={'category__title': 'Lembaga'}, on_delete=django.db.models.deletion.CASCADE, related_name='Jarnas_Category', to='elements.option'),
        ),
    ]
