# Generated by Django 4.2.4 on 2023-08-29 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0009_alter_respondent_gender_alter_respondent_jarnas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(limit_choices_to={'category__title': 'Jenis Layanan'}, on_delete=django.db.models.deletion.CASCADE, to='elements.option', verbose_name='Survey Title'),
        ),
    ]
