# Generated by Django 4.2.4 on 2023-08-29 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0010_alter_question_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Question_answer_Category', to='elements.option', verbose_name='Kategori Jawaban'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answer_choices', to='elements.option'),
        ),
    ]
