# Generated by Django 4.2.4 on 2023-08-29 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0011_remove_answer_timestamp_question_answer_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question_answer_Category', to='elements.category', verbose_name='Kategori Jawaban'),
        ),
    ]
