# Generated by Django 4.2.4 on 2023-08-30 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0013_question_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='survey',
            new_name='kategori',
        ),
    ]
