# Generated by Django 4.2.4 on 2023-08-30 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0014_rename_survey_question_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
