# Generated by Django 4.2.4 on 2023-08-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0021_alter_answer_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Jawaban Survey', 'verbose_name_plural': 'Jawaban Survey'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Provinsi/Kabupaten/Kota', 'verbose_name_plural': 'Provinsi/Kabupaten/Kota'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategori'},
        ),
        migrations.AlterModelOptions(
            name='faskes',
            options={'verbose_name': 'Fasilitas Kesehatan', 'verbose_name_plural': 'Fasilitas Kesehatan'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Opsi jawaban', 'verbose_name_plural': 'Opsi jawaban'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Publikasi', 'verbose_name_plural': 'Publikasi'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Pertanyaan Survey', 'verbose_name_plural': 'Pertanyaan Survey'},
        ),
        migrations.AlterModelOptions(
            name='respondent',
            options={'verbose_name': 'Responden Survey', 'verbose_name_plural': 'Responden Survey'},
        ),
        migrations.RenameField(
            model_name='respondent',
            old_name='nama',
            new_name='id_respondent',
        ),
    ]
